version = 1

[merge]
require_automerge_label = false
blacklist_labels = ["do not merge"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true

[update]
blacklist_usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]
