apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ikfram-secrets
  annotations:
    operator.1password.io/auto-restart: 'true'
spec:
  itemPath: vaults/idris/items/ikfram
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ikfram-config
data:
  APP_NAME: 'IKFRAM'
  APP_ENV: production
  APP_DEBUG: 'false'
  APP_URL: https://IKFRAM.wesl.io

  LOG_CHANNEL: daily

  # postgres
  DB_CONNECTION: pgsql
  DB_HOST: 10.0.0.2
  DB_PORT: '5432'
  DB_DATABASE: ikfram

  BROADCAST_DRIVER: 'null'
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: '120'

  #TRUSTED_PROXY_LIST: "10.0.1.0/24"
