apiVersion: v1
kind: Secret
metadata:
  name: ghcr-access-token
data:
  .dockerconfigjson: ENC[AES256_GCM,data:k/vfeO5a0EXCITySN6/ideIndEHKYcERXthxBybWlYtQvzPO5V9jv8gjQlfeglsk5UXeQudiyZRTa7nNaPGPIzFtOO7Lnwj1GcDyQ8YHDFL9ROG9yINYl5YqjX/5oUudSrvQfr40lWhfNVQzPViSfX6cKTQU24BdMNeKoCItEfCNyF5a3kGmelgSLioz7LndP8XF/ynmDEl3q3z5SeZWpp8+nF+02rE7phpZpV7ADCUht6rZII3qYk/5zQnFZGmnrBZyQRM5mLhAT6+EBjJ3umgc5m408dgjIBGpi7+sn0IQXsW8qeDc8vsMYz2gKzpdkD9vbSaiowijFq74Wis25sE7lbuyl/7MCPEGN1GZ+CleYNNDcsXG0ah6g8I=,iv:Ph8jW3PSvvJ8QSGLUW2EOgcJ3LM5I9TonVROB1SdKzQ=,tag:A3Sn1M0pTUKmA/Wt+A0ITg==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-01-11T11:22:09Z'
  mac: ENC[AES256_GCM,data:YcO/ze4p84SuaE6JHTLHOfoHayjmACfqArz/WO1y46e9HlHepZHt3hUYDjh1JrkQNkqSvBP8YqZIis93H+Mxx2nVyw90GN7dXaJZXua+8eiSpP7+UhFZOTsFcbrEjwEkR83BUTlrICoY9hkyEVhLfEjUvq1S8vRxSCuBEA81fbo=,iv:UTI/+lTnhUlB4nYKzDOUdFhC3XHz/yysCN+610c5LCM=,tag:lIJTjD8V4zeJT742SqrPhQ==,type:str]
  pgp:
    - created_at: '2022-01-11T11:22:09Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA9SfNNfXEmWKARAApacQGYq6xT64tU9wTDyzOqaB7Nnqmq4AVsZrlVxigIwc
        GWpeHFH166Q23ATuq9eV8jV0jFOAN7v46MsT8O4+Lw2ZwyPPb7SZrVz52JBFfpjQ
        HpuOtFx0ybUWjMsvHWkqmcsHmAmUvBfk4M2wMeWFF7IvfGfv2J/zhfbn0FdPRNR3
        x3s3F5D5z9kbxvyIASKv0zh0kp5wjko+Nhf8UaqxtP/m9ZeQmhtUT8bHZVCRQc7X
        0dE08rRmcvEZ/xZ6K1T34DS3dJ3IX2auA6WEKoyOEZpoE49ZNUdiXVHXFyFJhL35
        jYi8nMQ1pX2dyzK8gVhC0McB0pN09C4DXtRVUV3BrnFCix/0moa65iBqQX834/RR
        +jxsa817ZzAwemnLNFNv9Nep+vXj0zN4LMzFk6Hf0cJ1Sl4q80NagMIvqYc91n0I
        LV3kb4vfQNHqSmkj6KGCbpn4KZE8FKw3BFTQxunUziIJeaIz7PxNi8HopLz4ltvJ
        sjxZXETUD31dla4ciY/ZUrX/odCjK/rOPeo8G8/CQ62U4FG7b0jJfFuvORkkNvac
        QpglFCVAkU7BJ58Atbq/w89HoqXu6cBmUhuDOJ7WSgvdbUji4V6LXEQxOJF8Pk1x
        Psbm3kvPFtf5d/0+bFn1q+yhDyglTeUnvHsyy0C1NueX9BGD/C9VlVEMhMvKy0fS
        XgGaVbB15jxXGHbZmR02Irvvg2fvPwcZd+9EJHY0LO+aHs17OmxXamqC4KbAIBXG
        vevb+Nv38mFMwJH+h6BeAEd0iRsRWaj1eKGxUaAy/0FtD8CNgvFxVWe0jqg2f3Y=
        =3qC6
        -----END PGP MESSAGE-----
      fp: 08A206845A41CF2E937EC8E2AFB036649EF97CB6
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
