name: Automated tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  PHP_VERSION: 8.1

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Node version
        id: node-version
        run: echo "::set-output name=node-version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run lint:check
